// test file for qboardbatch
set x y
set pixmap dragway.jpg
new piece
set -point pos 80 20
set -int bogo 7

new piece
set pixmap "games/Joe/counters/002-bazooka.png"
set color #00ff00

/**
new piece
set pixmap games/Joe/counters/006-kneeler.png
set color #ff00ff
set colorAlpha 100
set angle 60
set pos 100 150

new piece
set pixmap games/Joe/counters/010-average1.png
set color 100 200 150
set angle 60
set colorAlpha 100
set borderColor red
set borderSize 5
set angle 170
set pos 100 100

**/

save /home/stephan/.QBoard/batch
//save
save timestamp
